# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      id: unit_test
      run: |
        pytest tests -v --cov=src --cov-report=html
      continue-on-error: true

    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: htmlcov
        path: htmlcov

    - name: Error handling
      if: ${{ steps.unit_test.outcome == 'failure' }}
      run: |
        echo "Error handling"
        echo ${{ steps.unit_test.outcome }}
        exit 1
